In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /Users/uginpo/anaconda3/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from openpyxl) (1.1.0)

In [33]:
!pip3 install sidetable

Collecting sidetable
  Downloading sidetable-0.9.1-py3-none-any.whl (19 kB)
Requirement already satisfied: pandas>=1.0 in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from sidetable) (2.0.1)
Requirement already satisfied: pytz>=2020.1 in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from pandas>=1.0->sidetable) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from pandas>=1.0->sidetable) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from pandas>=1.0->sidetable) (1.24.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from pandas>=1.0->sidetable) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/uginpo/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.0->sidetable) (1.16.0)
Installing collected packages: sidetable
Successfully installed sidetable-0.9.1

In [392]:
import pandas as pd
import numpy as np
import openpyxl
import xlsxwriter
import os.path
import sidetable
import locale
import sys

In [393]:
locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

'ru_RU.UTF-8'

In [444]:
path_to_data= f'/Users/uginpo/OneDrive - gxog/Отчеты ВБ/ООО Исток/Сведенные/2022/'
report__pivot='Сводный отчет.xlsx'
name__analitic='Аналитика.xlsx'

report_pivot = path_to_data + report__pivot
name_analitic = path_to_data + name__analitic

In [445]:
if os.path.isfile(name_analitic):
    df_analitic = pd.read_excel(name_analitic, sheet_name = [0,1], header=0)
else:
    df_analitic = False

Настройка параметров отчета

In [446]:
month_r='all'
date_start=''
date_final=''
period_r ='month' #'report'
goods_r='all'

In [490]:
month_d={'01':'Январь', '02':'Февраль', '03':'Март', '04':'Апрель','05': 'Май','06': 'Июнь',
         '07':'Июль','08': 'Август','09': 'Сентябрь','10': 'Октябрь','11': 'Ноябрь','12': 'Декабрь'}

In [491]:
sum_list=['Кол-во', 'Кол-во доставок', 'Кол-во возврата','Реализация ВБ', 'Вознаграждение ВБ',
         'Логистика','Очищенная выручка', 'Сумма закупки','Доход']
sum_list_pr=['Кол-во','Сумма закупки', 'Логистика', 'Хранение', 'Удержания','Очищенная выручка','Доход']

In [544]:
df_f=df_analitic[0].copy(deep=True)
df_pr_lost=df_analitic[1].copy(deep=True)

Формирование отчета по продажам

In [545]:
list_df=[df_f, df_pr_lost]

In [546]:
for df_ind in list_df:
    df_ind['Дата начала']= pd.to_datetime(df_ind['Дата начала'], format='%d/%m/%Y')
    df_ind["Месяц"]=df_ind['Дата начала'].dt.month.astype(str).str.zfill(2)    
        

year_f=df_f['Дата начала'].dt.year.astype(str)[0]

In [547]:
df_a=df_f.groupby(['Месяц','Артикул поставщика','Название'])[sum_list].sum()
df_pr_lost=df_pr_lost.groupby(['Месяц'])[sum_list_pr].sum()

In [549]:
df_pr_lost

,Кол-во,Сумма закупки,Логистика,Хранение,Удержания,Очищенная выручка,Доход
Месяц,,,,,,,
01,136,21852.56,9869.00,2018.84,0.00,24922.51,1051.11
02,879,160131.63,67487.00,5513.27,0.00,154510.97,-11133.93
03,2609,405299.20,151238.00,0.00,0.00,606251.68,200952.48
04,1405,233031.95,95757.00,8239.88,33.00,369210.93,127906.10
05,2853,366310.18,269168.50,27225.34,1460.81,575447.48,180451.15
06,2189,307378.07,157873.50,24839.73,2441.00,453393.62,118734.82
07,1595,208796.87,112892.00,28960.74,13954.70,368872.47,117160.16
08,1820,242991.63,178940.90,70536.23,184982.16,356390.88,-142119.14
09,1883,279697.89,215767.20,89041.06,283432.12,326628.86,-325542.21
10,4095,575716.75,522853.00,99920.14,6850.50,633309.94,-49177.45
11,2014,321173.02,436634.00,192974.01,-3306.50,115001.49,-395839.04
12,2709,374351.08,1408760.43,45289.03,2223729.88,-742599.30,-3385969.29

In [550]:
df_b=df_a.stb.subtotal(sub_level=[1], grand_label='Всего за период', sub_label= 'Итого за месяц')

In [551]:
df_b=df_b.reset_index()

In [552]:
df_b = df_b.rename(columns={"level_0": "Месяц", "level_1": "Артикул поставщика", "level_2": "Название"})

In [553]:
df_b

,Месяц,Артикул поставщика,Название,Кол-во,Кол-во доставок,Кол-во возврата,Реализация ВБ,Вознаграждение ВБ,Логистика,Очищенная выручка,Сумма закупки,Доход
0,01,BumStakanBelg250Bel,Стаканы одноразовые бумажные 260 мл / 50 шт.,3.0,4.0,0.0,761.40,48.60,220.00,492.80,284.43,208.37
1,01,BumStakanBelg250Siti,Стакан,7.0,7.0,0.0,1860.92,192.76,385.00,1283.16,663.67,619.49
2,01,BumStakanBelg250ZigZag,Стаканы одноразовые бумажные 250 мл / 50 шт,10.0,19.0,0.0,2181.91,62.39,1045.00,1074.52,948.10,126.42
3,01,Бум/Стак/Белгород/ХорДеньКрасн/250мл,Стакан,4.0,6.0,0.0,983.22,30.53,330.00,622.69,379.24,243.45
4,01,Бум/Стакан/Белгород/Крафт/250мл,Стаканы бумажные одноразовые 250 мл / 50 шт,2.0,3.0,0.0,510.30,31.32,165.00,313.98,189.62,124.36
...,...,...,...,...,...,...,...,...,...,...,...,...
2527,12,Эльсеф/Роскошь/Питания/400мл/1шт,Шампунь Роскошь питания 6 масел питательный 40...,10.0,9.0,2.0,5888.00,-132.62,3134.00,2886.62,2033.00,853.62
2528,12,Эльсеф/Эксперт/Цвета/окр/волос/400м,Шампунь Эксперт Цвета для окрашенных волос 400 мл,4.0,2.0,0.0,2340.01,-56.78,1600.00,796.79,813.20,-16.41
2529,12,для горячих и холодных напитков,Стаканы,44.0,78.0,1.0,9031.52,1632.45,21649.00,-14249.93,3740.00,-17989.93
2530,12,12 - Итого за месяц,,2709.0,4076.0,254.0,749854.52,83694.86,1408760.43,-742599.30,374351.08,-1116950.38
2531,Всего за период,,,24187.0,32458.0,1852.0,7054308.50,186084.23,3627240.53,3241341.53,3496730.83,-255389.30

In [554]:
df_pr_b=df_pr_lost.stb.subtotal(sub_level=[1], grand_label='Всего за период').reset_index()

In [556]:
df_pr_b = df_pr_b.rename(columns={"index": "Месяц"})
df_pr_b

,Месяц,Кол-во,Сумма закупки,Логистика,Хранение,Удержания,Очищенная выручка,Доход
0,01,136.0,21852.56,9869.00,2018.84,0.00,24922.51,1051.11
1,02,879.0,160131.63,67487.00,5513.27,0.00,154510.97,-11133.93
2,03,2609.0,405299.20,151238.00,0.00,0.00,606251.68,200952.48
3,04,1405.0,233031.95,95757.00,8239.88,33.00,369210.93,127906.10
4,05,2853.0,366310.18,269168.50,27225.34,1460.81,575447.48,180451.15
5,06,2189.0,307378.07,157873.50,24839.73,2441.00,453393.62,118734.82
6,07,1595.0,208796.87,112892.00,28960.74,13954.70,368872.47,117160.16
7,08,1820.0,242991.63,178940.90,70536.23,184982.16,356390.88,-142119.14
8,09,1883.0,279697.89,215767.20,89041.06,283432.12,326628.86,-325542.21
9,10,4095.0,575716.75,522853.00,99920.14,6850.50,633309.94,-49177.45
10,11,2014.0,321173.02,436634.00,192974.01,-3306.50,115001.49,-395839.04
11,12,2709.0,374351.08,1408760.43,45289.03,2223729.88,-742599.30,-3385969.29
12,Всего за период,24187.0,3496730.83,3627240.53,594558.27,2713577.67,3241341.53,-3563525.24

In [557]:
df_b = df_b.replace({'Месяц': month_d})
df_pr_b = df_pr_b.replace({'Месяц': month_d})

In [559]:
df_pr_b

,Месяц,Кол-во,Сумма закупки,Логистика,Хранение,Удержания,Очищенная выручка,Доход
0,Январь,136.0,21852.56,9869.00,2018.84,0.00,24922.51,1051.11
1,Февраль,879.0,160131.63,67487.00,5513.27,0.00,154510.97,-11133.93
2,Март,2609.0,405299.20,151238.00,0.00,0.00,606251.68,200952.48
3,Апрель,1405.0,233031.95,95757.00,8239.88,33.00,369210.93,127906.10
4,Май,2853.0,366310.18,269168.50,27225.34,1460.81,575447.48,180451.15
5,Июнь,2189.0,307378.07,157873.50,24839.73,2441.00,453393.62,118734.82
6,Июль,1595.0,208796.87,112892.00,28960.74,13954.70,368872.47,117160.16
7,Август,1820.0,242991.63,178940.90,70536.23,184982.16,356390.88,-142119.14
8,Сентябрь,1883.0,279697.89,215767.20,89041.06,283432.12,326628.86,-325542.21
9,Октябрь,4095.0,575716.75,522853.00,99920.14,6850.50,633309.94,-49177.45
10,Ноябрь,2014.0,321173.02,436634.00,192974.01,-3306.50,115001.49,-395839.04
11,Декабрь,2709.0,374351.08,1408760.43,45289.03,2223729.88,-742599.30,-3385969.29
12,Всего за период,24187.0,3496730.83,3627240.53,594558.27,2713577.67,3241341.53,-3563525.24

In [414]:
itog_str = f'- Итого за месяц'
df1 = df_b[df_b['Артикул поставщика'].str.contains(itog_str)]
ind=df1.index

In [574]:
df_b['Артикул поставщика'].where(~(df_b['Артикул поставщика'].str.contains(itog_str)), other='Итого за месяц', inplace=True)
df_b

,Месяц,Артикул поставщика,Название,Кол-во,Кол-во доставок,Кол-во возврата,Реализация ВБ,Вознаграждение ВБ,Логистика,Очищенная выручка,Сумма закупки,Доход
0,Январь,BumStakanBelg250Bel,Стаканы одноразовые бумажные 260 мл / 50 шт.,3.0,4.0,0.0,761.40,48.60,220.00,492.80,284.43,208.37
1,Январь,BumStakanBelg250Siti,Стакан,7.0,7.0,0.0,1860.92,192.76,385.00,1283.16,663.67,619.49
2,Январь,BumStakanBelg250ZigZag,Стаканы одноразовые бумажные 250 мл / 50 шт,10.0,19.0,0.0,2181.91,62.39,1045.00,1074.52,948.10,126.42
3,Январь,Бум/Стак/Белгород/ХорДеньКрасн/250мл,Стакан,4.0,6.0,0.0,983.22,30.53,330.00,622.69,379.24,243.45
4,Январь,Бум/Стакан/Белгород/Крафт/250мл,Стаканы бумажные одноразовые 250 мл / 50 шт,2.0,3.0,0.0,510.30,31.32,165.00,313.98,189.62,124.36
...,...,...,...,...,...,...,...,...,...,...,...,...
2527,Декабрь,Эльсеф/Роскошь/Питания/400мл/1шт,Шампунь Роскошь питания 6 масел питательный 40...,10.0,9.0,2.0,5888.00,-132.62,3134.00,2886.62,2033.00,853.62
2528,Декабрь,Эльсеф/Эксперт/Цвета/окр/волос/400м,Шампунь Эксперт Цвета для окрашенных волос 400 мл,4.0,2.0,0.0,2340.01,-56.78,1600.00,796.79,813.20,-16.41
2529,Декабрь,для горячих и холодных напитков,Стаканы,44.0,78.0,1.0,9031.52,1632.45,21649.00,-14249.93,3740.00,-17989.93
2530,Декабрь,Итого за месяц,,2709.0,4076.0,254.0,749854.52,83694.86,1408760.43,-742599.30,374351.08,-1116950.38
2531,Всего за период,,,24187.0,32458.0,1852.0,7054308.50,186084.23,3627240.53,3241341.53,3496730.83,-255389.30

In [582]:
with pd.ExcelWriter(report_pivot, engine='xlsxwriter') as wb:
    df_b.to_excel(wb, sheet_name='sales '+ year_f, index=False, float_format = "%0.2f")
    df_pr_b.to_excel(wb, sheet_name='profits '+ year_f, index=False, float_format = "%0.2f")
    sheet = wb.sheets['sales '+ year_f]
    sheet.set_column('A:A', 20)
    sheet.set_column('B:B', 30)
    sheet.set_column('C:C', 35)
    sheet.set_column('D:L', 15)
    
    cell_format = wb.book.add_format()
    cell_format.set_bold()
    cell_format.set_font_color('black')
    sheet.set_row(0, 30, cell_format) # Установка стиля для строки 2 и высоты 40
    #cell_format.set_bg_color('#FDCFC5')
    cell_format.set_font_size(14)
    cell_format.set_num_format(4)
    

    # Add a header format.
    header_format = wb.book.add_format({
        'bold': True,
        'text_wrap': True,
        'valign': 'center',
        'fg_color': '#D7E4BC',
        'border': 1,
        })
    header_format.set_align('top')
    header_format.set_font_size(14)
    sheet.set_row(0, 40, header_format)

    # Write the column headers with the defined format.
    for col_num, value in enumerate(df_b.columns.values):
        sheet.write(0, col_num, value, header_format)
    
    
    cell_format = wb.book.add_format()
    cell_format.set_bold()
    cell_format.set_font_color('black')
    for row_i in ind:
        sheet.set_row(row_i+1, 25, cell_format) # Установка стиля для строки 2 и высоты 40       
    
    cell_format.set_bg_color('#A3E2B9')
    
    
    cell_format = wb.book.add_format()
    cell_format.set_bold()
    cell_format.set_font_color('black')
    sheet.set_row(len(df_b), 30, cell_format) # Установка стиля для строки 2 и высоты 40
    cell_format.set_bg_color('#FDCFC5')
    cell_format.set_font_size(14)
    cell_format.set_num_format(4)
    
    
    # Форматирование второго листа
    sheet0=wb.sheets['profits '+ year_f]
    sheet0.set_column('A:H', 20)
    
    # Add a header format.
    header_format = wb.book.add_format({
        'bold': True,
        'text_wrap': True,
        'valign': 'center',
        'fg_color': '#D7E4BC',
        'border': 1,
        })
    header_format.set_align('top')
    header_format.set_font_size(14)
    sheet0.set_row(0, 40, header_format)

    # Write the column headers with the defined format.
    for col_num, value in enumerate(df_pr_b.columns.values):
        sheet0.write(0, col_num, value, header_format)
    
    cell_format = wb.book.add_format()
    cell_format.set_bold()
    cell_format.set_font_color('black')
    sheet0.set_row(len(df_pr_b), 30, cell_format) 
    cell_format.set_bg_color('#FDCFC5')
    cell_format.set_font_size(14)
    cell_format.set_num_format(4)
    
    # Add some cell formats.
    #format1 = wb.book.add_format({"num_format": "#,##0.00"})


    # Note: It isn't possible to format any cells that already have a format such
    # as the index or headers or any cells that contain dates or datetimes.

    # Set the column width and format.
    #sheet.set_column(1, 20, None, format1)
    #sheet0.set_column(1, 20, None, format1)